infile using "C:\USERS\21429\ICF\DATA ARCHIVE - DOCUMENTS\EXPORT MENU\CM81\CMPR81FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for man's interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "NA - Household selected for Domestic Violence module"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv047    "Team number"
label variable hv048    "NA - Team supervisor"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv201b   "NA - Water for drinking not sufficient in the last month"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv222    "Type of cookstove"
label variable hv223    "Type of cooking fuel"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv230a   "NA - Place where household members wash their hands"
label variable hv230b   "NA - Presence of water at hand washing place"
label variable hv232    "NA - Items present: Soap or detergent"
label variable hv232b   "NA - Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "NA - Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "NA - Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236a   "NA - Line number Person fetching water"
label variable hv237    "NA - Anything done to water to make safe to drink"
label variable hv237a   "NA - Water usually treated by: boil"
label variable hv237b   "NA - Water usually treated by: add bleach/chlorine"
label variable hv237c   "NA - Water usually treated by: strain through a cloth"
label variable hv237d   "NA - Water usually treated by: use water filter"
label variable hv237e   "NA - Water usually treated by: solar disinfection"
label variable hv237f   "NA - Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "NA - Water usually treated by: other"
label variable hv237z   "NA - Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Stove has a chimney"
label variable hv241    "NA - Food cooked in the house/ separate building/ outdoors"
label variable hv242    "NA - Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns Pig"
label variable hv246h   "NA - Owns CS"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv252    "NA - Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv255    "NA - Septic tank has been emptied"
label variable hv256    "NA - Septic tank emptied by a service provider"
label variable hv257    "NA - Where septic tanked emptied to"
label variable hv259    "NA - Heat source for home"
label variable hv260    "NA - Heat at home has a chimney"
label variable hv261    "NA - Type of fuel for home heat"
label variable hv262    "NA - Type of light at home"
label variable hv263    "NA - Mobile phone used financial transactions"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable sh116e   "Computer"
label variable sh116g   "Cooker"
label variable sh116h   "Gas stove"
label variable sh116i   "Air conditioner"
label variable sh116j   "Fan"
label variable sh116k   "Cd/dvd player"
label variable sh116l   "Grain mill/mixer"
label variable sh116m   "Modem/router"
label variable sh116n   "Cable network/satellite dish"
label variable sh116o   "Generator"
label variable sh116p   "Solar panel"
label variable sh116q   "Water pump"
label variable sh116r   "Clock"
label variable sh117a   "Watch"
label variable sh117h   "Laptop computer"
label variable sh117i   "Tablet computer"
label variable sh134a   "Any pools of stagnant water observed"
label variable sh134b   "Bushes/trees observed"
label variable sh134c   "Time to nearest public health facility (mins)"
label variable sh134d   "Time to nearest private health facility (mins)"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Stayed last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "NA - Highest educational level attained"
label variable hv107    "NA - Highest year of education completed"
label variable hv108    "NA - Education completed in single years"
label variable hv109    "NA - Educational attainment"
label variable hv110    "NA - Member still in school"
label variable hv111    "NA - Mother alive"
label variable hv112    "NA - Mother's line number"
label variable hv113    "NA - Father alive"
label variable hv114    "NA - Father's line number"
label variable hv115    "NA - Current marital status"
label variable hv116    "NA - Currently, formerly, never married"
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "NA - Member attended school during current school year"
label variable hv122    "NA - Educational level during current school year"
label variable hv123    "NA - Grade of education during current school year"
label variable hv124    "NA - Education in single years - current school year"
label variable hv125    "NA - Member attended school during previous school year"
label variable hv126    "NA - Educational level during previous school year"
label variable hv127    "NA - Grade of education during previous school year"
label variable hv128    "NA - Education in single years - previous school year"
label variable hv129    "NA - School attendance status"
label variable hv140    "NA - Member has a birth certificate"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc1a     "Child's age in days"
label variable hc2      "NA - Child's weight in kilograms (1 decimal)"
label variable hc2a     "NA - Child's weight in kilograms (1 decimal) - first measurement"
label variable hc2b     "NA - Child's weight in kilograms (1 decimal) - re-measurement"
label variable hc3      "NA - Child's height in centimeters (1 decimal)"
label variable hc3a     "NA - Child's height in centimeters (1 decimal) - first measurement"
label variable hc3b     "NA - Child's height in centimeters (1 decimal) - re-measurement"
label variable hc13     "Result of measurement - height/weight"
label variable hc15     "NA - Height: lying or standing"
label variable hc15a    "NA - Height: lying or standing - first measurement"
label variable hc15b    "NA - Height: lying or standing - re-measurement"
label variable hc16     "Day of birth"
label variable hc17     "NA - Date measured (day)"
label variable hc18     "NA - Date measured (month)"
label variable hc19     "NA - Date measured (year)"
label variable hc20     "Century Day Code (CDC) of measurement"
label variable hc21     "NA - Fieldworker measurer code for anthropometry"
label variable hc21a    "NA - Fieldworker assistant measurer code for anthropometry"
label variable hc21b    "Fieldworker measurer code for hemoglobin"
label variable hc22     "NA - Child minimally dressed"
label variable hc23     "NA - Correct measurement procedure used"
label variable hc24     "NA - Child's hair had braids or ornaments"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc32a    "Century Day Code (CDC) of birth"
label variable hc33     "Completeness of HC32 information"
label variable hc35     "NA - Reason for re-measurement"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable hc70     "Height/Age standard deviation (new WHO)"
label variable hc71     "Weight/Age standard deviation (new WHO)"
label variable hc72     "Weight/Height standard deviation (new WHO)"
label variable hc73     "BMI standard deviation (new WHO)"
label variable hmlidx   "Mosquito Bed Net Designation Number"
label variable hml3     "Net observed by interviewer"
label variable hml4     "Months ago net obtained"
label variable hml5     "NA - Net treated with insecticide when bought"
label variable hml6     "NA - Net treatment status"
label variable hml7     "Brand of net"
label variable hml8     "NA - Net treated since received"
label variable hml9     "NA - Time since last re-treatment (months)"
label variable hml10    "Insecticide-Treated Net (ITN)"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Someone slept under this net last night"
label variable hmla     "Line number of person who slept in this net"
label variable hmlb     "Line number of person who slept in this net"
label variable hmlc     "Line number of person who slept in this net"
label variable hmld     "Line number of person who slept in this net"
label variable hmle     "NA - Line number of person who slept in this net"
label variable hml22    "Obtained net from campaign, antenatal or immunization visit"
label variable hml23    "Place where net was obtained"
label variable hml24    "Reason net was not used"
label variable hmhidx   "Index to Household Schedule"
label variable hml12    "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15    "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16    "Corrected age from Individual file"
label variable hml16a   "Age in months (for children)"
label variable hml17    "Flag for age from Individual file"
label variable hml18    "Pregnancy status from Individual file"
label variable hml19    "Person slept under an ever-treated net"
label variable hml20    "Person slept under an LLIN net"
label variable hml30    "Line number of parent/caretaker (for malaria testing)"
label variable hml31    "Read consent statement for malaria"
label variable hml32    "NA - Final result of malaria from blood smear test"
label variable hml32a   "NA - Presence of species: falciparum (Pf)"
label variable hml32b   "NA - Presence of species: malariae (Pm)"
label variable hml32c   "NA - Presence of species: ovale (Po)"
label variable hml32d   "NA - Presence of species: vivax (Pv)"
label variable hml32e   "NA - Presence of species: CS"
label variable hml32f   "NA - Presence of species: CS"
label variable hml32g   "NA - Presence of species: CS"
label variable hml33    "NA - Result of malaria measurement"
label variable hml34    "Bar code for blood smear sample"
label variable hml35    "Result of malaria rapid test"
label variable hml36    "Fieldworker measurer code for malaria"
label variable hml37a   "Suffer from illness/symptom: extreme weakness"
label variable hml37b   "Suffer from illness/symptom: heart problems"
label variable hml37c   "Suffer from illness/symptom: loss of consciousness"
label variable hml37d   "Suffer from illness/symptom: rapid or difficult breathing"
label variable hml37e   "Suffer from illness/symptom: seizures"
label variable hml37f   "Suffer from illness/symptom: abnormal bleeding"
label variable hml37g   "Suffer from illness/symptom: jaundice or yellow skin"
label variable hml37h   "Suffer from illness/symptom: dark urine"
label variable hml37i   "NA - Suffer from illness/symptom: CS"
label variable hml37j   "NA - Suffer from illness/symptom: CS"
label variable hml37k   "NA - Suffer from illness/symptom: CS"
label variable hml37l   "NA - Suffer from illness/symptom: CS"
label variable hml37m   "NA - Suffer from illness/symptom: CS"
label variable hml38    "Child taken or taking first line medicine given by health provider for malaria"
label variable hml39    "Parent accept first line medicine to treat malaria"
label variable hml40    "Fieldworker provided first line medicine for malaria"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     1 "Adamaoua - Urban"
     2 "Adamaoua - Rural"
     3 "Centre (Excludes Yaounde) - Urban"
     4 "Centre (Excludes Yaounde) - Rural"
     5 "Douala - Urban"
     6 "East - Urban"
     7 "East - Rural"
     8 "Far North - Urban"
     9 "Far North - Rural"
    10 "Littoral (Excludes Douala) - Urban"
    11 "Littoral (Excludes Douala) - Rural"
    12 "North - Urban"
    13 "North - Rural"
    14 "North-West - Urban"
    15 "North-West - Rural"
    16 "West - Urban"
    17 "West - Rural"
    18 "South - Urban"
    19 "South - Rural"
    20 "South-West - Urban"
    21 "South-West - Rural"
    22 "Yaounde - Urban"
;
label define HV024   
     1 "Adamaoua"
     2 "Centre (Excludes Yaounde)"
     3 "Douala"
     4 "East"
     5 "Far North"
     6 "Littoral (Excludes Douala)"
     7 "North"
     8 "North-West"
     9 "West"
    10 "South"
    11 "South-West"
    12 "Yaounde"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV045A  
     1 "English"
     2 "French"
;
label define HV045B  
     1 "English"
     2 "French"
     3 "Fufulde"
     4 "Pidgin"
    96 "Other"
;
label define HV045C  
     1 "English"
     2 "French"
     3 "Fufulde"
     4 "Pidgin"
    96 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    92 "Sachet water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    92 "Sachet water"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
;
label define HV201B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL FLOOR"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY FLOOR"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED FLOOR"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Metal"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV222   
     1 "Electric stove"
     2 "Solar cooker"
     3 "Liquefied petroleum gas (LPG)/cooking gas stove"
     4 "Piped natural gas stove"
     5 "Biogas stove"
     6 "Liquid fuel stove"
     7 "Manufactured solid fuel stove"
     8 "Traditional solid fuel stove"
     9 "Three stone stove/open fire"
    95 "No food cooked in household"
    96 "Other"
;
label define HV223   
     1 "Alcohol/ethanol"
     2 "Gasoline/diesel"
     3 "Kerosene/paraffin"
     4 "Coal/lignite"
     5 "Charcoal"
     6 "Wood"
     7 "Straw/shrubs/grass"
     8 "Agricultural crop"
     9 "Animal dung/waste"
    10 "Processed biomass (pellets) or woodchips"
    11 "Garbage/plastic"
    12 "Sawdust"
    96 "Other"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "Solar energy"
     3 "Liquefied petroleum gas (LPG)/cooking gas"
     4 "Piped natural gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed, fixed place"
     2 "Observed, mobile place"
     3 "Not observed: not in dwelling"
     4 "Not observed: no permission to see"
     5 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "household uses salt but no salt available"
     4 "Household does not use salt"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236A  
     0 "Not a household member"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than once a month"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV255   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV256   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV257   
     1 "Treatment plant"
     2 "Buried in a covered pit"
     3 "Uncovered pit/bush/field/open ground"
     4 "Surface water (river/dam/lake/pond/stream/canal/irrigation channel)"
     6 "Other"
     8 "Don't know"
;
label define HV259   
     1 "Central heating"
     2 "Manufactured space heater"
     3 "Traditional space heater"
     4 "Manufactured cookstove"
     5 "Traditional cookstove"
     6 "Three stone stove/open fire"
    95 "No space heating in household"
    96 "Other"
;
label define HV260   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV261   
     1 "Electricity"
     2 "Piped natural gas"
     3 "Solar air heater"
     4 "Liquefied petroleum gas (LPG)/cooking gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No heating in household"
    96 "Other"
;
label define HV262   
     1 "Electricity"
     2 "Solar lantern"
     3 "Rechargeable flashlight, torch, or lantern"
     4 "Battery powered flashlight, torch or lantern"
     5 "Biogas lamp"
     6 "Gasoline lamp"
     7 "Kerosene or paraffin lamp"
     8 "Charcoal"
     9 "Wood"
    10 "Straw/shrubs/grass"
    11 "Agricultural crop"
    12 "Animal dung/waste"
    13 "Oil lamp"
    14 "Candle"
    95 "No lighting in household"
    96 "Other"
;
label define HV263   
     0 "No"
     1 "Yes"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SH116E  
     1 "Yes"
     0 "No"
;
label define SH116G  
     1 "Yes"
     0 "No"
;
label define SH116H  
     1 "Yes"
     0 "No"
;
label define SH116I  
     1 "Yes"
     0 "No"
;
label define SH116J  
     1 "Yes"
     0 "No"
;
label define SH116K  
     1 "Yes"
     0 "No"
;
label define SH116L  
     1 "Yes"
     0 "No"
;
label define SH116M  
     1 "Yes"
     0 "No"
;
label define SH116N  
     1 "Yes"
     0 "No"
;
label define SH116O  
     1 "Yes"
     0 "No"
;
label define SH116P  
     1 "Yes"
     0 "No"
;
label define SH116Q  
     1 "Yes"
     0 "No"
;
label define SH116R  
     1 "Yes"
     0 "No"
;
label define SH117A  
     1 "Yes"
     0 "No"
;
label define SH117H  
     1 "Yes"
     0 "No"
;
label define SH117I  
     1 "Yes"
     0 "No"
;
label define SH134A  
     1 "STAGNANT WATER OBSERVED"
     0 "NO STAGNANT WATER OBSERVED"
;
label define SH134B  
     1 "BUSHES / TREES OBSERVED"
     0 "NO BUSHES / TREES OBSERVED"
;
label define SH134C  
   998 "Don't know"
;
label define SH134D  
   998 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool/early childhood education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool/early childhood education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool/early childhood education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC2A    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC2B    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3A    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3B    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC15A   
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC15B   
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC22    
     0 "No"
     1 "Yes"
;
label define HC23    
     0 "No"
     1 "Yes"
;
label define HC24    
     0 "No"
     1 "Yes"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC35    
     0 "Not remeasured"
     1 "Random"
     2 "Z-Scores"
     3 "Both random & Z-scores"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "1st secondary cycle"
     3 "2nd secondary cycle"
     4 "Higher"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    10 "Long-lasting insecticide treated nets (LLIN)"
    11 "Olyset Net"
    12 "Olyset Plus"
    13 "Permanet"
    14 "Duranet"
    15 "Yorkool"
    16 "Dawa Plus"
    17 "Interceptor"
    18 "Royal Sentry"
    19 "Royal Guard"
    20 "Magnet"
    21 "Veeralin"
    22 "Yahe LLIN"
    23 "Safi Net"
    24 "Panda Net"
    26 "Other/Don't know brand (LLIN)"
    30 "Pretreated net"
    96 "Other brand"
    98 "DK brand"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML22   
     0 "No"
     1 "Yes, campaign"
     2 "Yes, antenatal care"
     3 "Yes, immunization visit"
;
label define HML23   
    10 "Government health facility"
    20 "Private health facility"
    30 "Other sources"
    31 "Pharmacy"
    32 "Shop/market"
    33 "CHW"
    34 "Religious institution"
    35 "School"
     7 "Association/NGO"
     8 "Parent/Friend"
    96 "Other"
    98 "Don't know"
;
label define HML24   
     1 "Don't like net shape"
     2 "Don't like net colour"
     3 "Don't like net material"
     4 "Don't like net size"
     5 "Don't like smell"
     6 "Unable to hang net"
     7 "Slept outdoors"
     8 "Usual user didn't sleep here last night"
     9 "No mosquitoes/no malaria"
    10 "Extra net/saving for later"
    11 "Spread in the sun/washed"
    12 "Don't like mosquito net/heat/stifling"
    13 "Old"
    14 "Not installed/Not spread in the open air"
    96 "Other"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML37A  
     0 "No"
     1 "Yes"
;
label define HML37B  
     0 "No"
     1 "Yes"
;
label define HML37C  
     0 "No"
     1 "Yes"
;
label define HML37D  
     0 "No"
     1 "Yes"
;
label define HML37E  
     0 "No"
     1 "Yes"
;
label define HML37F  
     0 "No"
     1 "Yes"
;
label define HML37G  
     0 "No"
     1 "Yes"
;
label define HML37H  
     0 "No"
     1 "Yes"
;
label define HML37I  
     0 "No"
     1 "Yes"
;
label define HML37J  
     0 "No"
     1 "Yes"
;
label define HML37K  
     0 "No"
     1 "Yes"
;
label define HML37L  
     0 "No"
     1 "Yes"
;
label define HML37M  
     0 "No"
     1 "Yes"
;
label define HML38   
     0 "No"
     1 "Yes"
;
label define HML39   
     0 "Refused medicine"
     1 "Accepted medicine"
     6 "Other"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv201b   HV201B  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv222    HV222   
label values hv223    HV223   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236a   HV236A  
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv238a   HV238A  
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv255    HV255   
label values hv256    HV256   
label values hv257    HV257   
label values hv259    HV259   
label values hv260    HV260   
label values hv261    HV261   
label values hv262    HV262   
label values hv263    HV263   
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values sh116e   SH116E  
label values sh116g   SH116G  
label values sh116h   SH116H  
label values sh116i   SH116I  
label values sh116j   SH116J  
label values sh116k   SH116K  
label values sh116l   SH116L  
label values sh116m   SH116M  
label values sh116n   SH116N  
label values sh116o   SH116O  
label values sh116p   SH116P  
label values sh116q   SH116Q  
label values sh116r   SH116R  
label values sh117a   SH117A  
label values sh117h   SH117H  
label values sh117i   SH117I  
label values sh134a   SH134A  
label values sh134b   SH134B  
label values sh134c   SH134C  
label values sh134d   SH134D  
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv140    HV140   
label values hc2      HC2     
label values hc2a     HC2A    
label values hc2b     HC2B    
label values hc3      HC3     
label values hc3a     HC3A    
label values hc3b     HC3B    
label values hc13     HC13    
label values hc15     HC15    
label values hc15a    HC15A   
label values hc15b    HC15B   
label values hc16     HC16    
label values hc22     HC22    
label values hc23     HC23    
label values hc24     HC24    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc35     HC35    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml22    HML22   
label values hml23    HML23   
label values hml24    HML24   
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hml20    HML20   
label values hml30    HML30   
label values hml31    HML31   
label values hml32    HML32   
label values hml32a   HML32A  
label values hml32b   HML32B  
label values hml32c   HML32C  
label values hml32d   HML32D  
label values hml32e   HML32E  
label values hml32f   HML32F  
label values hml32g   HML32G  
label values hml33    HML33   
label values hml35    HML35   
label values hml37a   HML37A  
label values hml37b   HML37B  
label values hml37c   HML37C  
label values hml37d   HML37D  
label values hml37e   HML37E  
label values hml37f   HML37F  
label values hml37g   HML37G  
label values hml37h   HML37H  
label values hml37i   HML37I  
label values hml37j   HML37J  
label values hml37k   HML37K  
label values hml37l   HML37L  
label values hml37m   HML37M  
label values hml38    HML38   
label values hml39    HML39   
