DATA LIST FILE='C:\USERS\21429\ICF\DATA ARCHIVE - DOCUMENTS\EXPORT MENU\CM81\CMPR81FL.DAT' RECORDS=1
 /
 HHID        1-12   (A)
 HVIDX      13-14  
 HV000      15-17   (A)
 HV001      18-23  
 HV002      24-29  
 HV003      30-32  
 HV004      33-36  
 HV005      37-44  
 HV006      45-46  
 HV007      47-50  
 HV008      51-54  
 HV008A     55-59  
 HV009      60-61  
 HV010      62-63  
 HV011      64-65  
 HV012      66-67  
 HV013      68-69  
 HV014      70-71  
 HV015      72-72  
 HV016      73-74  
 HV017      75-75  
 HV018      76-80  
 HV019      81-83  
 HV020      84-84  
 HV021      85-88  
 HV022      89-92  
 HV023      93-96  
 HV024      97-98  
 HV025      99-99  
 HV026     100-100 
 HV027     101-101 
 HV028     102-109 
 HV030     110-114 
 HV031     115-119 
 HV032     120-122 
 HV035     123-124 
 HV040     125-128 
 HV041     129-130 
 HV042     131-131 
 HV044     132-132 
 HV045A    133-135 
 HV045B    136-138 
 HV045C    139-141 
 HV046     142-142 
 HV047     143-147 
 HV048     148-152 
 HV801     153-156 
 HV802     157-160 
 HV803     161-162 
 HV804     163-163 
 HV807D    164-165 
 HV807M    166-167 
 HV807Y    168-171 
 HV807C    172-175 
 HV807A    176-180 
 HV201     181-182 
 HV202     183-184 
 HV201A    185-185 
 HV201B    186-186 
 HV204     187-189 
 HV205     190-191 
 HV206     192-192 
 HV207     193-193 
 HV208     194-194 
 HV209     195-195 
 HV210     196-196 
 HV211     197-197 
 HV212     198-198 
 HV213     199-200 
 HV214     201-202 
 HV215     203-204 
 HV216     205-206 
 HV217     207-207 
 HV218     208-209 
 HV219     210-210 
 HV220     211-212 
 HV221     213-213 
 HV222     214-215 
 HV223     216-217 
 HV225     218-218 
 HV226     219-220 
 HV227     221-221 
 HV228     222-222 
 HV230A    223-223 
 HV230B    224-224 
 HV232     225-225 
 HV232B    226-226 
 HV232C    227-227 
 HV232D    228-228 
 HV232E    229-229 
 HV232Y    230-230 
 HV234     231-233 
 HV234A    234-234 
 HV235     235-235 
 HV236A    236-237 
 HV237     238-238 
 HV237A    239-239 
 HV237B    240-240 
 HV237C    241-241 
 HV237D    242-242 
 HV237E    243-243 
 HV237F    244-244 
 HV237G    245-245 
 HV237H    246-246 
 HV237I    247-247 
 HV237J    248-248 
 HV237K    249-249 
 HV237X    250-250 
 HV237Z    251-251 
 HV238     252-253 
 HV238A    254-254 
 HV239     255-255 
 HV240     256-256 
 HV241     257-257 
 HV242     258-258 
 HV243A    259-259 
 HV243B    260-260 
 HV243C    261-261 
 HV243D    262-262 
 HV243E    263-263 
 HV244     264-264 
 HV245     265-267 
 HV246     268-268 
 HV246A    269-270 
 HV246B    271-272 
 HV246C    273-274 
 HV246D    275-276 
 HV246E    277-278 
 HV246F    279-280 
 HV246G    281-282 
 HV246H    283-284 
 HV246I    285-286 
 HV246J    287-288 
 HV246K    289-290 
 HV247     291-291 
 HV252     292-292 
 HV253     293-293 
 HV253A    294-294 
 HV253B    295-295 
 HV253C    296-296 
 HV253D    297-297 
 HV253E    298-298 
 HV253F    299-299 
 HV253G    300-300 
 HV253H    301-301 
 HV253X    302-302 
 HV253Z    303-303 
 HV255     304-304 
 HV256     305-305 
 HV257     306-306 
 HV259     307-308 
 HV260     309-309 
 HV261     310-311 
 HV262     312-313 
 HV263     314-314 
 HV270     315-315 
 HV271     316-323 
 HV270A    324-324 
 HV271A    325-332 
 HML1      333-334 
 HML1A     335-335 
 HML2      336-337 
 SH116E    338-338 
 SH116G    339-339 
 SH116H    340-340 
 SH116I    341-341 
 SH116J    342-342 
 SH116K    343-343 
 SH116L    344-344 
 SH116M    345-345 
 SH116N    346-346 
 SH116O    347-347 
 SH116P    348-348 
 SH116Q    349-349 
 SH116R    350-350 
 SH117A    351-351 
 SH117H    352-352 
 SH117I    353-353 
 SH134A    354-354 
 SH134B    355-355 
 SH134C    356-358 
 SH134D    359-361 
 HV101     362-363 
 HV102     364-364 
 HV103     365-365 
 HV104     366-366 
 HV105     367-368 
 HV106     369-369 
 HV107     370-371 
 HV108     372-373 
 HV109     374-374 
 HV110     375-375 
 HV111     376-376 
 HV112     377-378 
 HV113     379-379 
 HV114     380-381 
 HV115     382-382 
 HV116     383-383 
 HV117     384-384 
 HV118     385-385 
 HV120     386-386 
 HV121     387-387 
 HV122     388-388 
 HV123     389-390 
 HV124     391-392 
 HV125     393-393 
 HV126     394-394 
 HV127     395-396 
 HV128     397-398 
 HV129     399-399 
 HV140     400-400 
 HC0       401-402 
 HC1       403-404 
 HC1A      405-409 
 HC2       410-413 
 HC2A      414-417 
 HC2B      418-421 
 HC3       422-425 
 HC3A      426-429 
 HC3B      430-433 
 HC13      434-434 
 HC15      435-435 
 HC15A     436-436 
 HC15B     437-437 
 HC16      438-439 
 HC17      440-441 
 HC18      442-443 
 HC19      444-447 
 HC20      448-452 
 HC21      453-457 
 HC21A     458-462 
 HC21B     463-467 
 HC22      468-468 
 HC23      469-469 
 HC24      470-470 
 HC27      471-471 
 HC30      472-473 
 HC31      474-477 
 HC32      478-481 
 HC32A     482-486 
 HC33      487-487 
 HC35      488-488 
 HC51      489-490 
 HC52      491-491 
 HC53      492-494 
 HC55      495-495 
 HC56      496-498 
 HC57      499-499 
 HC58      500-500 
 HC60      501-503 
 HC61      504-504 
 HC62      505-506 
 HC63      507-509 
 HC64      510-511 
 HC68      512-512 
 HC70      513-516 
 HC71      517-520 
 HC72      521-524 
 HC73      525-528 
 HMLIDX    529-530 
 HML3      531-531 
 HML4      532-533 
 HML5      534-534 
 HML6      535-535 
 HML7      536-537 
 HML8      538-538 
 HML9      539-540 
 HML10     541-541 
 HML11     542-542 
 HML21     543-543 
 HMLA      544-545 
 HMLB      546-547 
 HMLC      548-549 
 HMLD      550-551 
 HMLE      552-553 
 HML22     554-554 
 HML23     555-556 
 HML24     557-558 
 HMHIDX    559-560 
 HML12     561-561 
 HML13     562-562 
 HML14     563-563 
 HML15     564-564 
 HML16     565-566 
 HML16A    567-568 
 HML17     569-569 
 HML18     570-570 
 HML19     571-571 
 HML20     572-572 
 HML30     573-574 
 HML31     575-575 
 HML32     576-576 
 HML32A    577-577 
 HML32B    578-578 
 HML32C    579-579 
 HML32D    580-580 
 HML32E    581-581 
 HML32F    582-582 
 HML32G    583-583 
 HML33     584-584 
 HML34     585-589  (A)
 HML35     590-590 
 HML36     591-595 
 HML37A    596-596 
 HML37B    597-597 
 HML37C    598-598 
 HML37D    599-599 
 HML37E    600-600 
 HML37F    601-601 
 HML37G    602-602 
 HML37H    603-603 
 HML37I    604-604 
 HML37J    605-605 
 HML37K    606-606 
 HML37L    607-607 
 HML37M    608-608 
 HML38     609-609 
 HML39     610-610 
 HML40     611-615 
.
VARIABLE LABELS
  HHID     "Case Identification"
 /HVIDX    "Line number"
 /HV000    "Country code and phase"
 /HV001    "Cluster number"
 /HV002    "Household number"
 /HV003    "Respondent's line number (answering Household questionnaire)"
 /HV004    "Ultimate area unit"
 /HV005    "Household sample weight (6 decimals)"
 /HV006    "Month of interview"
 /HV007    "Year of interview"
 /HV008    "Date of interview (CMC)"
 /HV008A   "Date of interview Century Day Code (CDC)"
 /HV009    "Number of household members"
 /HV010    "Number of eligible women in household"
 /HV011    "Number of eligible men in household"
 /HV012    "Number of de jure members"
 /HV013    "Number of de facto members"
 /HV014    "Number of children 5 and under (de jure)"
 /HV015    "Result of household interview"
 /HV016    "Day of interview"
 /HV017    "Number of visits"
 /HV018    "Interviewer identification"
 /HV019    "NA - Keyer identification"
 /HV020    "Ever-married sample"
 /HV021    "Primary sampling unit"
 /HV022    "Sample strata for sampling errors"
 /HV023    "Stratification used in sample design"
 /HV024    "Region"
 /HV025    "Type of place of residence"
 /HV026    "NA - Place of residence"
 /HV027    "Household selected for man's interview"
 /HV028    "Household weight for male subsample (6 decimals)"
 /HV030    "Field supervisor"
 /HV031    "NA - Field editor"
 /HV032    "NA - Office editor"
 /HV035    "Number of eligible children for height and weight"
 /HV040    "Cluster altitude in meters"
 /HV041    "NA - Total adults measured"
 /HV042    "Household selected for hemoglobin"
 /HV044    "NA - Household selected for Domestic Violence module"
 /HV045A   "Language of questionnaire"
 /HV045B   "Language of interview"
 /HV045C   "Native language of respondent"
 /HV046    "Translator used"
 /HV047    "Team number"
 /HV048    "NA - Team supervisor"
 /HV801    "Time interview started (hhmm - 24 hour clock)"
 /HV802    "Time interview ended (hhmm - 24 hour clock)"
 /HV803    "Length of interview in minutes"
 /HV804    "Number of visits for biomarker"
 /HV807D   "Day of biomarker visit"
 /HV807M   "Month of biomarker visit"
 /HV807Y   "Year of biomarker visit"
 /HV807C   "Date of biomarker (CMC)"
 /HV807A   "Date of biomarker Century Day Code (CDC)"
 /HV201    "Source of drinking water"
 /HV202    "Source of non-drinking water"
 /HV201A   "NA - Water not available for at least a day last two weeks"
 /HV201B   "NA - Water for drinking not sufficient in the last month"
 /HV204    "Time to get to water source (minutes)"
 /HV205    "Type of toilet facility"
 /HV206    "Has electricity"
 /HV207    "Has radio"
 /HV208    "Has television"
 /HV209    "Has refrigerator"
 /HV210    "Has bicycle"
 /HV211    "Has motorcycle/scooter"
 /HV212    "Has car/truck"
 /HV213    "Main floor material"
 /HV214    "Main wall material"
 /HV215    "Main roof material"
 /HV216    "Number of rooms used for sleeping"
 /HV217    "Relationship structure"
 /HV218    "Line number of head of household"
 /HV219    "Sex of head of household"
 /HV220    "Age of head of household"
 /HV221    "Has telephone (land-line)"
 /HV222    "Type of cookstove"
 /HV223    "Type of cooking fuel"
 /HV225    "Share toilet with other households"
 /HV226    "Type of cooking fuel"
 /HV227    "Has mosquito bed net for sleeping"
 /HV228    "Children under 5 slept under mosquito bed net last night"
 /HV230A   "NA - Place where household members wash their hands"
 /HV230B   "NA - Presence of water at hand washing place"
 /HV232    "NA - Items present: Soap or detergent"
 /HV232B   "NA - Items present: Ash, mud, sand"
 /HV232C   "NA - Items present: CS"
 /HV232D   "NA - Items present: CS"
 /HV232E   "NA - Items present: CS"
 /HV232Y   "NA - Items present: None"
 /HV234    "NA - Result of salt test for iodine (PPM)"
 /HV234A   "NA - Result of salt test for iodine"
 /HV235    "Location of source for water"
 /HV236A   "NA - Line number Person fetching water"
 /HV237    "NA - Anything done to water to make safe to drink"
 /HV237A   "NA - Water usually treated by: boil"
 /HV237B   "NA - Water usually treated by: add bleach/chlorine"
 /HV237C   "NA - Water usually treated by: strain through a cloth"
 /HV237D   "NA - Water usually treated by: use water filter"
 /HV237E   "NA - Water usually treated by: solar disinfection"
 /HV237F   "NA - Water usually treated by: let it stand and settle"
 /HV237G   "NA - Water usually treated by: CS"
 /HV237H   "NA - Water usually treated by: CS"
 /HV237I   "NA - Water usually treated by: CS"
 /HV237J   "NA - Water usually treated by: CS"
 /HV237K   "NA - Water usually treated by: CS"
 /HV237X   "NA - Water usually treated by: other"
 /HV237Z   "NA - Water usually treated by: don't know"
 /HV238    "Number of households sharing toilet"
 /HV238A   "Location of toilet facility"
 /HV239    "NA - Food cooked on stove or open fire"
 /HV240    "NA - Stove has a chimney"
 /HV241    "NA - Food cooked in the house/ separate building/ outdoors"
 /HV242    "NA - Household has separate room used as kitchen"
 /HV243A   "Has mobile telephone"
 /HV243B   "Has watch"
 /HV243C   "Has animal-drawn cart"
 /HV243D   "Has boat with a motor"
 /HV243E   "Has a computer"
 /HV244    "Owns land usable for agriculture"
 /HV245    "Hectares of agricultural land (1 decimal)"
 /HV246    "Owns livestock, herds or farm animals"
 /HV246A   "Owns cattle"
 /HV246B   "Owns cows/ bulls"
 /HV246C   "Owns horses/ donkeys/ mules"
 /HV246D   "Owns goats"
 /HV246E   "Owns sheep"
 /HV246F   "Owns chickens/poultry"
 /HV246G   "Owns Pig"
 /HV246H   "NA - Owns CS"
 /HV246I   "NA - Owns CS"
 /HV246J   "NA - Owns CS"
 /HV246K   "NA - Owns CS"
 /HV247    "Has bank account"
 /HV252    "NA - Frequency household members smoke inside the house"
 /HV253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
 /HV253A   "NA - Dwelling sprayed by: government worker/program"
 /HV253B   "NA - Dwelling sprayed by: private company"
 /HV253C   "NA - Dwelling sprayed by: NGO"
 /HV253D   "NA - Dwelling sprayed by: CS"
 /HV253E   "NA - Dwelling sprayed by: CS"
 /HV253F   "NA - Dwelling sprayed by: CS"
 /HV253G   "NA - Dwelling sprayed by: CS"
 /HV253H   "NA - Dwelling sprayed by: CS"
 /HV253X   "NA - Dwelling sprayed by: other"
 /HV253Z   "NA - Dwelling sprayed by: don't know"
 /HV255    "NA - Septic tank has been emptied"
 /HV256    "NA - Septic tank emptied by a service provider"
 /HV257    "NA - Where septic tanked emptied to"
 /HV259    "NA - Heat source for home"
 /HV260    "NA - Heat at home has a chimney"
 /HV261    "NA - Type of fuel for home heat"
 /HV262    "NA - Type of light at home"
 /HV263    "NA - Mobile phone used financial transactions"
 /HV270    "Wealth index combined"
 /HV271    "Wealth index factor score combined (5 decimals)"
 /HV270A   "Wealth index for urban/rural"
 /HV271A   "Wealth index factor score for urban/rural (5 decimals)"
 /HML1     "Number of mosquito bed nets"
 /HML1A    "Number of mosquito bed nets with specific information"
 /HML2     "Number of children under mosquito bed net previous night"
 /SH116E   "Computer"
 /SH116G   "Cooker"
 /SH116H   "Gas stove"
 /SH116I   "Air conditioner"
 /SH116J   "Fan"
 /SH116K   "Cd/dvd player"
 /SH116L   "Grain mill/mixer"
 /SH116M   "Modem/router"
 /SH116N   "Cable network/satellite dish"
 /SH116O   "Generator"
 /SH116P   "Solar panel"
 /SH116Q   "Water pump"
 /SH116R   "Clock"
 /SH117A   "Watch"
 /SH117H   "Laptop computer"
 /SH117I   "Tablet computer"
 /SH134A   "Any pools of stagnant water observed"
 /SH134B   "Bushes/trees observed"
 /SH134C   "Time to nearest public health facility (mins)"
 /SH134D   "Time to nearest private health facility (mins)"
 /HV101    "Relationship to head"
 /HV102    "Usual resident"
 /HV103    "Stayed last night"
 /HV104    "Sex of household member"
 /HV105    "Age of household members"
 /HV106    "NA - Highest educational level attained"
 /HV107    "NA - Highest year of education completed"
 /HV108    "NA - Education completed in single years"
 /HV109    "NA - Educational attainment"
 /HV110    "NA - Member still in school"
 /HV111    "NA - Mother alive"
 /HV112    "NA - Mother's line number"
 /HV113    "NA - Father alive"
 /HV114    "NA - Father's line number"
 /HV115    "NA - Current marital status"
 /HV116    "NA - Currently, formerly, never married"
 /HV117    "Eligibility for female interview"
 /HV118    "Eligibility for male interview"
 /HV120    "Children eligibility for height/weight and hemoglobin"
 /HV121    "NA - Member attended school during current school year"
 /HV122    "NA - Educational level during current school year"
 /HV123    "NA - Grade of education during current school year"
 /HV124    "NA - Education in single years - current school year"
 /HV125    "NA - Member attended school during previous school year"
 /HV126    "NA - Educational level during previous school year"
 /HV127    "NA - Grade of education during previous school year"
 /HV128    "NA - Education in single years - previous school year"
 /HV129    "NA - School attendance status"
 /HV140    "NA - Member has a birth certificate"
 /HC0      "Index to Household Schedule"
 /HC1      "Child's age in months"
 /HC1A     "Child's age in days"
 /HC2      "NA - Child's weight in kilograms (1 decimal)"
 /HC2A     "NA - Child's weight in kilograms (1 decimal) - first measurement"
 /HC2B     "NA - Child's weight in kilograms (1 decimal) - re-measurement"
 /HC3      "NA - Child's height in centimeters (1 decimal)"
 /HC3A     "NA - Child's height in centimeters (1 decimal) - first measurement"
 /HC3B     "NA - Child's height in centimeters (1 decimal) - re-measurement"
 /HC13     "Result of measurement - height/weight"
 /HC15     "NA - Height: lying or standing"
 /HC15A    "NA - Height: lying or standing - first measurement"
 /HC15B    "NA - Height: lying or standing - re-measurement"
 /HC16     "Day of birth"
 /HC17     "NA - Date measured (day)"
 /HC18     "NA - Date measured (month)"
 /HC19     "NA - Date measured (year)"
 /HC20     "Century Day Code (CDC) of measurement"
 /HC21     "NA - Fieldworker measurer code for anthropometry"
 /HC21A    "NA - Fieldworker assistant measurer code for anthropometry"
 /HC21B    "Fieldworker measurer code for hemoglobin"
 /HC22     "NA - Child minimally dressed"
 /HC23     "NA - Correct measurement procedure used"
 /HC24     "NA - Child's hair had braids or ornaments"
 /HC27     "Sex"
 /HC30     "Month of birth"
 /HC31     "Year of birth"
 /HC32     "Date of birth (CMC)"
 /HC32A    "Century Day Code (CDC) of birth"
 /HC33     "Completeness of HC32 information"
 /HC35     "NA - Reason for re-measurement"
 /HC51     "Line number of parent/caretaker"
 /HC52     "Read consent statement - hemoglobin"
 /HC53     "Hemoglobin level (g/dl - 1 decimal)"
 /HC55     "Result of measurement - hemoglobin"
 /HC56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
 /HC57     "Anemia level"
 /HC58     "NA - Agrees to referral - anemia"
 /HC60     "Mother's line number (woman's questionnaire)"
 /HC61     "Mother's highest educational level"
 /HC62     "Mother's highest year of education"
 /HC63     "Preceding birth interval (months)"
 /HC64     "Birth order number"
 /HC68     "Mother's highest educational level (for preliminary and final report)"
 /HC70     "Height/Age standard deviation (new WHO)"
 /HC71     "Weight/Age standard deviation (new WHO)"
 /HC72     "Weight/Height standard deviation (new WHO)"
 /HC73     "BMI standard deviation (new WHO)"
 /HMLIDX   "Mosquito Bed Net Designation Number"
 /HML3     "Net observed by interviewer"
 /HML4     "Months ago net obtained"
 /HML5     "NA - Net treated with insecticide when bought"
 /HML6     "NA - Net treatment status"
 /HML7     "Brand of net"
 /HML8     "NA - Net treated since received"
 /HML9     "NA - Time since last re-treatment (months)"
 /HML10    "Insecticide-Treated Net (ITN)"
 /HML11    "Number of persons who slept under this net"
 /HML21    "Someone slept under this net last night"
 /HMLA     "Line number of person who slept in this net"
 /HMLB     "Line number of person who slept in this net"
 /HMLC     "Line number of person who slept in this net"
 /HMLD     "Line number of person who slept in this net"
 /HMLE     "NA - Line number of person who slept in this net"
 /HML22    "Obtained net from campaign, antenatal or immunization visit"
 /HML23    "Place where net was obtained"
 /HML24    "Reason net was not used"
 /HMHIDX   "Index to Household Schedule"
 /HML12    "Type of Mosquito Bed Net(s) person slept under last night"
 /HML13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
 /HML14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
 /HML15    "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
 /HML16    "Corrected age from Individual file"
 /HML16A   "Age in months (for children)"
 /HML17    "Flag for age from Individual file"
 /HML18    "Pregnancy status from Individual file"
 /HML19    "Person slept under an ever-treated net"
 /HML20    "Person slept under an LLIN net"
 /HML30    "Line number of parent/caretaker (for malaria testing)"
 /HML31    "Read consent statement for malaria"
 /HML32    "NA - Final result of malaria from blood smear test"
 /HML32A   "NA - Presence of species: falciparum (Pf)"
 /HML32B   "NA - Presence of species: malariae (Pm)"
 /HML32C   "NA - Presence of species: ovale (Po)"
 /HML32D   "NA - Presence of species: vivax (Pv)"
 /HML32E   "NA - Presence of species: CS"
 /HML32F   "NA - Presence of species: CS"
 /HML32G   "NA - Presence of species: CS"
 /HML33    "NA - Result of malaria measurement"
 /HML34    "Bar code for blood smear sample"
 /HML35    "Result of malaria rapid test"
 /HML36    "Fieldworker measurer code for malaria"
 /HML37A   "Suffer from illness/symptom: extreme weakness"
 /HML37B   "Suffer from illness/symptom: heart problems"
 /HML37C   "Suffer from illness/symptom: loss of consciousness"
 /HML37D   "Suffer from illness/symptom: rapid or difficult breathing"
 /HML37E   "Suffer from illness/symptom: seizures"
 /HML37F   "Suffer from illness/symptom: abnormal bleeding"
 /HML37G   "Suffer from illness/symptom: jaundice or yellow skin"
 /HML37H   "Suffer from illness/symptom: dark urine"
 /HML37I   "NA - Suffer from illness/symptom: CS"
 /HML37J   "NA - Suffer from illness/symptom: CS"
 /HML37K   "NA - Suffer from illness/symptom: CS"
 /HML37L   "NA - Suffer from illness/symptom: CS"
 /HML37M   "NA - Suffer from illness/symptom: CS"
 /HML38    "Child taken or taking first line medicine given by health provider for malaria"
 /HML39    "Parent accept first line medicine to treat malaria"
 /HML40    "Fieldworker provided first line medicine for malaria"
.
MISSING VALUE
  HV017    (9)
 /HV026    (9)
 /HV040    (9999)
 /HV801    (9999)
 /HV802    (9999)
 /HV803    (99)
 /HV804    (9)
 /HV201    (99)
 /HV202    (99)
 /HV201A   (9)
 /HV201B   (9)
 /HV204    (999)
 /HV205    (99)
 /HV206    (9)
 /HV207    (9)
 /HV208    (9)
 /HV209    (9)
 /HV210    (9)
 /HV211    (9)
 /HV212    (9)
 /HV213    (99)
 /HV214    (99)
 /HV215    (99)
 /HV216    (99)
 /HV219    (9)
 /HV220    (99)
 /HV221    (9)
 /HV225    (9)
 /HV226    (99)
 /HV227    (9)
 /HV228    (9)
 /HV230A   (9)
 /HV230B   (9)
 /HV232    (9)
 /HV232B   (9)
 /HV232C   (9)
 /HV232D   (9)
 /HV232E   (9)
 /HV232Y   (9)
 /HV234    (999)
 /HV234A   (9)
 /HV235    (9)
 /HV236A   (99)
 /HV237    (9)
 /HV237A   (9)
 /HV237B   (9)
 /HV237C   (9)
 /HV237D   (9)
 /HV237E   (9)
 /HV237F   (9)
 /HV237G   (9)
 /HV237H   (9)
 /HV237I   (9)
 /HV237J   (9)
 /HV237K   (9)
 /HV237X   (9)
 /HV237Z   (9)
 /HV238    (99)
 /HV238A   (9)
 /HV239    (9)
 /HV240    (9)
 /HV241    (9)
 /HV242    (9)
 /HV243A   (9)
 /HV243B   (9)
 /HV243C   (9)
 /HV243D   (9)
 /HV243E   (9)
 /HV244    (9)
 /HV245    (999)
 /HV246    (9)
 /HV246A   (99)
 /HV246B   (99)
 /HV246C   (99)
 /HV246D   (99)
 /HV246E   (99)
 /HV246F   (99)
 /HV246G   (99)
 /HV246H   (99)
 /HV246I   (99)
 /HV246J   (99)
 /HV246K   (99)
 /HV247    (9)
 /HV252    (9)
 /HV253    (9)
 /HV253A   (9)
 /HV253B   (9)
 /HV253C   (9)
 /HV253D   (9)
 /HV253E   (9)
 /HV253F   (9)
 /HV253G   (9)
 /HV253H   (9)
 /HV253X   (9)
 /HV253Z   (9)
 /HML1     (99)
 /HML2     (99)
 /HV101    (99)
 /HV102    (9)
 /HV103    (9)
 /HV104    (9)
 /HV105    (99)
 /HV106    (9)
 /HV107    (99)
 /HV108    (99)
 /HV109    (9)
 /HV110    (9)
 /HV111    (9)
 /HV112    (99)
 /HV113    (9)
 /HV114    (99)
 /HV115    (9)
 /HV116    (9)
 /HV121    (9)
 /HV122    (9)
 /HV123    (99)
 /HV124    (99)
 /HV125    (9)
 /HV126    (9)
 /HV127    (99)
 /HV128    (99)
 /HV129    (9)
 /HV140    (9)
 /HC2      (9999)
 /HC2A     (9999)
 /HC2B     (9999)
 /HC3      (9999)
 /HC3A     (9999)
 /HC3B     (9999)
 /HC13     (9)
 /HC15     (9)
 /HC15A    (9)
 /HC15B    (9)
 /HC16     (99)
 /HC27     (9)
 /HC30     (99)
 /HC31     (9999)
 /HC51     (99)
 /HC52     (9)
 /HC53     (999)
 /HC55     (9)
 /HC56     (999)
 /HC57     (9)
 /HC58     (9)
 /HC60     (999)
 /HC61     (9)
 /HC62     (99)
 /HC63     (999)
 /HC64     (99)
 /HC68     (9)
 /HC70     (9999)
 /HC71     (9999)
 /HC72     (9999)
 /HC73     (9999)
 /HML3     (9)
 /HML4     (99)
 /HML5     (9)
 /HML6     (9)
 /HML7     (99)
 /HML8     (9)
 /HML9     (99)
 /HML10    (9)
 /HML11    (9)
 /HML21    (9)
 /HMLA     (99)
 /HMLB     (99)
 /HMLC     (99)
 /HML22    (9)
 /HML23    (99)
 /HML12    (9)
 /HML16    (99)
 /HML18    (9)
 /HML31    (9)
 /HML32    (9)
 /HML32A   (9)
 /HML32B   (9)
 /HML32C   (9)
 /HML32D   (9)
 /HML32E   (9)
 /HML32F   (9)
 /HML32G   (9)
 /HML33    (9)
 /HML35    (9)
 /HML37A   (9)
 /HML37B   (9)
 /HML37C   (9)
 /HML37D   (9)
 /HML37E   (9)
 /HML37F   (9)
 /HML37G   (9)
 /HML37H   (9)
 /HML37I   (9)
 /HML37J   (9)
 /HML37K   (9)
 /HML37L   (9)
 /HML37M   (9)
 /HML38    (9)
 /HML39    (9)
.
VALUE LABELS
  HV003   
     0 "Incomplete household"
 /HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
 /HV020   
     0 "All woman sample"
     1 "Ever married sample"
 /HV023   
     1 "Adamaoua - Urban"
     2 "Adamaoua - Rural"
     3 "Centre (Excludes Yaounde) - Urban"
     4 "Centre (Excludes Yaounde) - Rural"
     5 "Douala - Urban"
     6 "East - Urban"
     7 "East - Rural"
     8 "Far North - Urban"
     9 "Far North - Rural"
    10 "Littoral (Excludes Douala) - Urban"
    11 "Littoral (Excludes Douala) - Rural"
    12 "North - Urban"
    13 "North - Rural"
    14 "North-West - Urban"
    15 "North-West - Rural"
    16 "West - Urban"
    17 "West - Rural"
    18 "South - Urban"
    19 "South - Rural"
    20 "South-West - Urban"
    21 "South-West - Rural"
    22 "Yaounde - Urban"
 /HV024   
     1 "Adamaoua"
     2 "Centre (Excludes Yaounde)"
     3 "Douala"
     4 "East"
     5 "Far North"
     6 "Littoral (Excludes Douala)"
     7 "North"
     8 "North-West"
     9 "West"
    10 "South"
    11 "South-West"
    12 "Yaounde"
 /HV025   
     1 "Urban"
     2 "Rural"
 /HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
 /HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
 /HV042   
     0 "Not selected"
     1 "Selected"
 /HV044   
     0 "Household not selected"
     1 "Household selected"
 /HV045A  
     1 "English"
     2 "French"
 /HV045B  
     1 "English"
     2 "French"
     3 "Fufulde"
     4 "Pidgin"
    96 "Other"
 /HV045C  
     1 "English"
     2 "French"
     3 "Fufulde"
     4 "Pidgin"
    96 "Other"
 /HV046   
     0 "No"
     1 "Yes"
 /HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
 /HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    92 "Sachet water"
    96 "Other"
 /HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    92 "Sachet water"
    96 "Other"
 /HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
 /HV201B  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV204   
   996 "On premises"
   998 "Don't know"
 /HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
 /HV206   
     0 "No"
     1 "Yes"
 /HV207   
     0 "No"
     1 "Yes"
 /HV208   
     0 "No"
     1 "Yes"
 /HV209   
     0 "No"
     1 "Yes"
 /HV210   
     0 "No"
     1 "Yes"
 /HV211   
     0 "No"
     1 "Yes"
 /HV212   
     0 "No"
     1 "Yes"
 /HV213   
    10 "NATURAL FLOOR"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY FLOOR"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED FLOOR"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
 /HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
 /HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Metal"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
 /HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
 /HV219   
     1 "Male"
     2 "Female"
 /HV220   
    97 "97+"
    98 "Don't know"
 /HV221   
     0 "No"
     1 "Yes"
 /HV222   
     1 "Electric stove"
     2 "Solar cooker"
     3 "Liquefied petroleum gas (LPG)/cooking gas stove"
     4 "Piped natural gas stove"
     5 "Biogas stove"
     6 "Liquid fuel stove"
     7 "Manufactured solid fuel stove"
     8 "Traditional solid fuel stove"
     9 "Three stone stove/open fire"
    95 "No food cooked in household"
    96 "Other"
 /HV223   
     1 "Alcohol/ethanol"
     2 "Gasoline/diesel"
     3 "Kerosene/paraffin"
     4 "Coal/lignite"
     5 "Charcoal"
     6 "Wood"
     7 "Straw/shrubs/grass"
     8 "Agricultural crop"
     9 "Animal dung/waste"
    10 "Processed biomass (pellets) or woodchips"
    11 "Garbage/plastic"
    12 "Sawdust"
    96 "Other"
 /HV225   
     0 "No"
     1 "Yes"
 /HV226   
     1 "Electricity"
     2 "Solar energy"
     3 "Liquefied petroleum gas (LPG)/cooking gas"
     4 "Piped natural gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No food cooked in house"
    96 "Other"
 /HV227   
     0 "No"
     1 "Yes"
 /HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
 /HV230A  
     1 "Observed, fixed place"
     2 "Observed, mobile place"
     3 "Not observed: not in dwelling"
     4 "Not observed: no permission to see"
     5 "Not observed: other reason"
 /HV230B  
     0 "Water not available"
     1 "Water is available"
 /HV232   
     0 "No"
     1 "Yes"
 /HV232B  
     0 "No"
     1 "Yes"
 /HV232C  
     0 "No"
     1 "Yes"
 /HV232D  
     0 "No"
     1 "Yes"
 /HV232E  
     0 "No"
     1 "Yes"
 /HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
 /HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
 /HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "household uses salt but no salt available"
     4 "Household does not use salt"
     6 "Salt not tested"
 /HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
 /HV236A  
     0 "Not a household member"
 /HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
 /HV238   
    95 "10 or more households"
    98 "Don't know"
 /HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
 /HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
 /HV240   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
 /HV242   
     0 "No"
     1 "Yes"
 /HV243A  
     0 "No"
     1 "Yes"
 /HV243B  
     0 "No"
     1 "Yes"
 /HV243C  
     0 "No"
     1 "Yes"
 /HV243D  
     0 "No"
     1 "Yes"
 /HV243E  
     0 "No"
     1 "Yes"
 /HV244   
     0 "No"
     1 "Yes"
 /HV245   
   950 "95 or more"
   998 "Unknown"
 /HV246   
     0 "No"
     1 "Yes"
 /HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
 /HV247   
     0 "No"
     1 "Yes"
 /HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than once a month"
 /HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
 /HV255   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV256   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV257   
     1 "Treatment plant"
     2 "Buried in a covered pit"
     3 "Uncovered pit/bush/field/open ground"
     4 "Surface water (river/dam/lake/pond/stream/canal/irrigation channel)"
     6 "Other"
     8 "Don't know"
 /HV259   
     1 "Central heating"
     2 "Manufactured space heater"
     3 "Traditional space heater"
     4 "Manufactured cookstove"
     5 "Traditional cookstove"
     6 "Three stone stove/open fire"
    95 "No space heating in household"
    96 "Other"
 /HV260   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV261   
     1 "Electricity"
     2 "Piped natural gas"
     3 "Solar air heater"
     4 "Liquefied petroleum gas (LPG)/cooking gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No heating in household"
    96 "Other"
 /HV262   
     1 "Electricity"
     2 "Solar lantern"
     3 "Rechargeable flashlight, torch, or lantern"
     4 "Battery powered flashlight, torch or lantern"
     5 "Biogas lamp"
     6 "Gasoline lamp"
     7 "Kerosene or paraffin lamp"
     8 "Charcoal"
     9 "Wood"
    10 "Straw/shrubs/grass"
    11 "Agricultural crop"
    12 "Animal dung/waste"
    13 "Oil lamp"
    14 "Candle"
    95 "No lighting in household"
    96 "Other"
 /HV263   
     0 "No"
     1 "Yes"
 /HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
 /HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
 /HML1    
    98 "Don't know"
 /SH116E  
     1 "Yes"
     0 "No"
 /SH116G  
     1 "Yes"
     0 "No"
 /SH116H  
     1 "Yes"
     0 "No"
 /SH116I  
     1 "Yes"
     0 "No"
 /SH116J  
     1 "Yes"
     0 "No"
 /SH116K  
     1 "Yes"
     0 "No"
 /SH116L  
     1 "Yes"
     0 "No"
 /SH116M  
     1 "Yes"
     0 "No"
 /SH116N  
     1 "Yes"
     0 "No"
 /SH116O  
     1 "Yes"
     0 "No"
 /SH116P  
     1 "Yes"
     0 "No"
 /SH116Q  
     1 "Yes"
     0 "No"
 /SH116R  
     1 "Yes"
     0 "No"
 /SH117A  
     1 "Yes"
     0 "No"
 /SH117H  
     1 "Yes"
     0 "No"
 /SH117I  
     1 "Yes"
     0 "No"
 /SH134A  
     1 "STAGNANT WATER OBSERVED"
     0 "NO STAGNANT WATER OBSERVED"
 /SH134B  
     1 "BUSHES / TREES OBSERVED"
     0 "NO BUSHES / TREES OBSERVED"
 /SH134C  
   998 "Don't know"
 /SH134D  
   998 "Don't know"
 /HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
 /HV102   
     0 "No"
     1 "Yes"
 /HV103   
     0 "No"
     1 "Yes"
 /HV104   
     1 "Male"
     2 "Female"
 /HV105   
    95 "95+"
    98 "Don't know"
 /HV106   
     0 "No education, preschool/early childhood education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
 /HV107   
    98 "Don't know"
 /HV108   
    97 "Inconsistent"
    98 "Don't know"
 /HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
 /HV110   
     0 "No"
     1 "Yes"
 /HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV112   
     0 "Mother not in household"
 /HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HV114   
     0 "Father not in household"
 /HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
 /HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
 /HV117   
     0 "Not eligible"
     1 "Eligible"
 /HV118   
     0 "Not eligible"
     1 "Eligible"
 /HV120   
     0 "Not eligible"
     1 "Eligible"
 /HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
 /HV122   
     0 "No education, preschool/early childhood education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
 /HV123   
    98 "Don't know"
 /HV124   
    97 "Inconsistent"
    98 "Don't know"
 /HV125   
     0 "No"
     1 "Yes"
 /HV126   
     0 "No education, preschool/early childhood education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
 /HV127   
    98 "Don't know"
 /HV128   
    97 "Inconsistent"
    98 "Don't know"
 /HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
 /HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
 /HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
 /HC2A    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
 /HC2B    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
 /HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
 /HC3A    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
 /HC3B    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
 /HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
 /HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
 /HC15A   
     0 "Not measured"
     1 "Lying"
     2 "Standing"
 /HC15B   
     0 "Not measured"
     1 "Lying"
     2 "Standing"
 /HC16    
    97 "Inconsistent"
    98 "Don't know"
 /HC22    
     0 "No"
     1 "Yes"
 /HC23    
     0 "No"
     1 "Yes"
 /HC24    
     0 "No"
     1 "Yes"
 /HC27    
     1 "Male"
     2 "Female"
 /HC30    
    97 "Inconsistent"
    98 "Don't know"
 /HC31    
  9997 "Inconsistent"
  9998 "Don't know"
 /HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
 /HC35    
     0 "Not remeasured"
     1 "Random"
     2 "Z-Scores"
     3 "Both random & Z-scores"
 /HC51    
     0 "Not in household"
 /HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
 /HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
 /HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
 /HC56    
   997 "Inconsistent"
 /HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
 /HC58    
     0 "No"
     1 "Yes"
 /HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
 /HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
 /HC62    
    98 "Don't know"
 /HC68    
     0 "No education"
     1 "Primary"
     2 "1st secondary cycle"
     3 "2nd secondary cycle"
     4 "Higher"
     8 "Don't know"
 /HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
 /HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
 /HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
 /HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
 /HML3    
     0 "Not seen"
     1 "Yes, seen"
 /HML4    
    96 "More than 3 years ago"
    98 "Don't know"
 /HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
 /HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
 /HML7    
    10 "Long-lasting insecticide treated nets (LLIN)"
    11 "Olyset Net"
    12 "Olyset Plus"
    13 "Permanet"
    14 "Duranet"
    15 "Yorkool"
    16 "Dawa Plus"
    17 "Interceptor"
    18 "Royal Sentry"
    19 "Royal Guard"
    20 "Magnet"
    21 "Veeralin"
    22 "Yahe LLIN"
    23 "Safi Net"
    24 "Panda Net"
    26 "Other/Don't know brand (LLIN)"
    30 "Pretreated net"
    96 "Other brand"
    98 "DK brand"
 /HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
 /HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
 /HML10   
     0 "No, don't know"
     1 "Yes"
 /HML11   
     5 "5+"
 /HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
 /HMLA    
     0 "No one"
 /HML22   
     0 "No"
     1 "Yes, campaign"
     2 "Yes, antenatal care"
     3 "Yes, immunization visit"
 /HML23   
    10 "Government health facility"
    20 "Private health facility"
    30 "Other sources"
    31 "Pharmacy"
    32 "Shop/market"
    33 "CHW"
    34 "Religious institution"
    35 "School"
     7 "Association/NGO"
     8 "Parent/Friend"
    96 "Other"
    98 "Don't know"
 /HML24   
     1 "Don't like net shape"
     2 "Don't like net colour"
     3 "Don't like net material"
     4 "Don't like net size"
     5 "Don't like smell"
     6 "Unable to hang net"
     7 "Slept outdoors"
     8 "Usual user didn't sleep here last night"
     9 "No mosquitoes/no malaria"
    10 "Extra net/saving for later"
    11 "Spread in the sun/washed"
    12 "Don't like mosquito net/heat/stifling"
    13 "Old"
    14 "Not installed/Not spread in the open air"
    96 "Other"
 /HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
 /HML13   
     0 "Did not sleep under net"
 /HML16   
    97 "97+"
    98 "Don't know"
 /HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
 /HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
 /HML19   
     0 "No"
     1 "Yes"
 /HML20   
     0 "No"
     1 "Yes"
 /HML30   
     0 "Not in household"
 /HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
 /HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
 /HML32A  
     0 "No"
     1 "Yes"
 /HML32B  
     0 "No"
     1 "Yes"
 /HML32C  
     0 "No"
     1 "Yes"
 /HML32D  
     0 "No"
     1 "Yes"
 /HML32E  
     0 "No"
     1 "Yes"
 /HML32F  
     0 "No"
     1 "Yes"
 /HML32G  
     0 "No"
     1 "Yes"
 /HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
 /HML34   
  99993 "Sample damaged/insufficient/not found in lab"
  99994 "Not present"
  99995 "Refused"
  99996 "Other"
  '?    ' "Missing"
 /HML35   
     0 "Negative"
     1 "Positive"
     3 "Not present"
     4 "Refused"
     6 "Other"
 /HML37A  
     0 "No"
     1 "Yes"
 /HML37B  
     0 "No"
     1 "Yes"
 /HML37C  
     0 "No"
     1 "Yes"
 /HML37D  
     0 "No"
     1 "Yes"
 /HML37E  
     0 "No"
     1 "Yes"
 /HML37F  
     0 "No"
     1 "Yes"
 /HML37G  
     0 "No"
     1 "Yes"
 /HML37H  
     0 "No"
     1 "Yes"
 /HML37I  
     0 "No"
     1 "Yes"
 /HML37J  
     0 "No"
     1 "Yes"
 /HML37K  
     0 "No"
     1 "Yes"
 /HML37L  
     0 "No"
     1 "Yes"
 /HML37M  
     0 "No"
     1 "Yes"
 /HML38   
     0 "No"
     1 "Yes"
 /HML39   
     0 "Refused medicine"
     1 "Accepted medicine"
     6 "Other"
.
EXECUTE.
